version: '3'

services:
    db:
        build:
            context: db
            dockerfile: Dockerfile
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 111111
            MYSQL_DATABASE: test
        security_opt:
            - seccomp:unconfined
        ports:
            - 3306:3306
        volumes: 
            - ./db/storage:/var/lib/mysql

    pma:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 4333:80
        depends_on:
            - db